@startuml
actor 教师 as teacher
participant "教师服务" as teacherService
participant "课程服务" as courseService
participant "房间占用服务" as roomOccupancyService
participant "数据库" as database

teacher -> teacherService : 请求预定
teacherService -> courseService : 获取课程信息
courseService -> database : 查询课程
database --> courseService : 课程数据
courseService --> teacherService : 返回课程信息
teacherService -> roomOccupancyService : 获取房间占用信息
roomOccupancyService -> database : 查询房间
database --> roomOccupancyService : 房间数据
roomOccupancyService --> teacherService : 返回房间信息
teacherService --> teacher : 返回预定结果

@enduml
